package org.techstartingpoint.javagraphlib.components;

import org.techstartingpoint.javagraphlib.graph.AbstractMainExecutor;

public class Filter extends AbstractMainExecutor {
    public String getName() {return "Filter";}

    public int getTotalInputPorts() {
        return 1;
    }

    public int getTotalOutputPorts() {
        return 1;
    }


    @Override
    protected void runMain() throws Exception {
        System.out.println("Filter");
        System.out.println(this.getEnvironmentKey());
        System.out.println(this.getNodeConfiguration());
        this.setOutputValue(0,"generated by filter component");
        // DO SOMETHING
        System.out.println("input:"+this.getTotalInputPorts());
        System.out.println("output:"+this.getTotalOutputPorts());
        this.setOutputValue(0,"Filter Value");
        System.out.println("input:"+this.getInputValue(0));
    }


}
