package org.techstartingpoint.javagraphlib.components;

import org.techstartingpoint.javagraphlib.graph.AbstractMainExecutor;

public class Filter extends AbstractMainExecutor {

    private static Class[] inputClasses={String.class};
    private static Class[] outputClasses={String.class};
    public Class[] getInputClasses() {return inputClasses;}
    public Class[] getOutputClasses() {return outputClasses;}

    public String getName() {return "Filter";}


    @Override
    protected void runMain() throws Exception {
        System.out.println("Filter");
        System.out.println(this.getEnvironmentKey());
        System.out.println(this.getNodeConfiguration());
        this.setOutputValue(0,"generated by filter component");
        // DO SOMETHING
        System.out.println("input:"+this.getTotalInputPorts());
        System.out.println("output:"+this.getTotalOutputPorts());
        this.setOutputValue(0,"Filter Value");
        System.out.println("input:"+this.getInputValue(0));
    }


}
