package com.onelake.workflowexecutor.components.mock;

import com.onelake.workflowexecutor.api.AbstractMainExecutor;

public class FilterMock extends AbstractMainExecutor {

    private static Class[] inputClasses={String.class};
    private static Class[] outputClasses={String.class};
    public Class[] getInputClasses() {return inputClasses;}
    public Class[] getOutputClasses() {return outputClasses;}

    public String getName() {return "FilterMock";}


    @Override
    protected void runMain()  {
        System.out.println("FilterMock");
        System.out.println(this.getEnvironmentKey());
        System.out.println(this.getNodeConfiguration());
        this.setOutputValue(0,"generated by filter component");
        // DO SOMETHING
        System.out.println("input:"+this.getTotalInputPorts());
        System.out.println("output:"+this.getTotalOutputPorts());
        this.setOutputValue(0,"FilterMock Value");
        System.out.println("input:"+this.getInputValue(0));
    }


}
