package com.onelake.workflowexecutor.components.mock;

import com.onelake.workflowexecutor.api.AbstractMainExecutor;

public class ReadFileMock extends AbstractMainExecutor {

    public ReadFileMock() {}

    private static Class[] inputClasses={};
    private static Class[] outputClasses={String.class};
    public Class[] getInputClasses() {return inputClasses;}
    public Class[] getOutputClasses() {return outputClasses;}

    public String getName() {return "ReadFileMock";}


    @Override
    protected void runMain()  {
        System.out.println("ReadFileMock");
        System.out.println(this.getEnvironmentKey());
        System.out.println(this.getNodeConfiguration());
        this.setOutputValue(0,"generated by read component");
        System.out.println("input:"+this.getTotalInputPorts());
        System.out.println("output:"+this.getTotalOutputPorts());
    }


}
